// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFkvbDBP7d6HPTcqOHQURZvJBZ96_-vdI',
    appId: '1:271303804122:web:c6b50351fdea0eb94091e3',
    messagingSenderId: '271303804122',
    projectId: 'bovmanager',
    authDomain: 'bovmanager.firebaseapp.com',
    storageBucket: 'bovmanager.firebasestorage.app',
    measurementId: 'G-YL4KSYHFSN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6Qa5yiqmEZ_KRZMfY0L3RRHEDBC8iS7s',
    appId: '1:271303804122:android:8bb1cc655e2cad0e4091e3',
    messagingSenderId: '271303804122',
    projectId: 'bovmanager',
    storageBucket: 'bovmanager.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDshaFqmLSG0T_SsWbviFfBUqHu8wmSCqQ',
    appId: '1:271303804122:ios:9de9fe8de9ce89104091e3',
    messagingSenderId: '271303804122',
    projectId: 'bovmanager',
    storageBucket: 'bovmanager.firebasestorage.app',
    iosBundleId: 'com.example.bovManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDshaFqmLSG0T_SsWbviFfBUqHu8wmSCqQ',
    appId: '1:271303804122:ios:9de9fe8de9ce89104091e3',
    messagingSenderId: '271303804122',
    projectId: 'bovmanager',
    storageBucket: 'bovmanager.firebasestorage.app',
    iosBundleId: 'com.example.bovManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFkvbDBP7d6HPTcqOHQURZvJBZ96_-vdI',
    appId: '1:271303804122:web:f56b95826469192c4091e3',
    messagingSenderId: '271303804122',
    projectId: 'bovmanager',
    authDomain: 'bovmanager.firebaseapp.com',
    storageBucket: 'bovmanager.firebasestorage.app',
    measurementId: 'G-D99VE8VD04',
  );
}
